sudo: required
services:
  - docker

before_install:
  - docker build -t jaibone/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jaibone/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-472044471290"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWSAccessKey
  secret_access_key: $AWSSecretKey
